### ISSUE TITLE
Instant Pay buttons not working on test environment

### ISSUE THREAD

**Issue by collymore** [Adyen/adyen-magento2-express-checkout#33] opened 2023-06-19 07:50 UTC
We've installed the Magento 2 instant pay buttons on our Magento 2.4.5-p2 site and we are trying to verify that the instant pay buttons work before going live. 

But we're unable to make any successful test purchases using Google or Apple Pay buttons. 

There are no errors displayed in the console or on the server logs when testing. 

Google Pay : Button renders correctly, and when clicked it shows dialog  but then closes when clicking Pay. There are no console or server logs. 

Apple Pay : Button renders correctly, Apple pay dialog opens, it's possible to select payment method, address etc,  but then there's no button rendered to complete transactions.

Apple Pay
<img width="551" alt="Screenshot 2023-06-19 at 08 44 38" src="https://github.com/Adyen/adyen-magento2-express-checkout/assets/55946/4c8a80bc-cdd5-4d17-b07b-a3e5b8e9846f">

Google Pay
<img width="1126" alt="Screenshot 2023-06-19 at 08 47 57" src="https://github.com/Adyen/adyen-magento2-express-checkout/assets/55946/f0809c2a-433b-478e-bdc2-3ac4c2d3cba0">

**Comment by candemiralp** [comment] 2023-08-29 14:25
Hello @collymore,

Thank you for raising this issue and apologies for late response. Unfortunately, we are not able reproduce your issue. For further investigation, could you please create a support ticket via support@adyen.com?

Closing this issue since we expect a reproducible error, some exception message and code references in Github issues. This issue will be carefully handled by our support engineers once you sent an email to us.

Best Regards,
Can

**Closed by candemiralp** 2023-08-29 14:25 UTC
