### ISSUE TITLE
Upon selecting the custom shipping method and proceeding to use Google Pay Express Checkout, the process fails, and users are unable to complete their transactions.

### ISSUE THREAD

**Issue by meetvora69** [Adyen/adyen-magento2-express-checkout#85] opened 2024-03-29 10:55 UTC
Currently, when users click on the Google Pay Express Checkout button, a popup is supposed to open displaying relevant information. However, we've noticed that when a custom shipping method is selected, the popup closes abruptly within a second without any error message.

This issue does not occur when the default shipping method provided by Magento is enabled, indicating that there might be an inconsistency between our custom shipping method and the Google Pay Express Checkout functionality.

We would greatly appreciate your assistance in diagnosing and resolving this issue promptly to ensure a seamless checkout experience for our customers. Could you please investigate the compatibility of our custom shipping method with the Google Pay Express Checkout feature and provide any necessary guidance or adjustments needed to rectify this problem?

1. Visit the cart page.
2. Click on the Google Pay Express Checkout button.
3. Upon clicking the Google Pay Express Checkout button, a popup window opens as expected.
4. However, the popup unexpectedly closes automatically after appro
5. We've thoroughly checked the console for errors, but no relevant error messages are displayed.
6. Additionally, our investigation extends to the Adyen log, which also does not provide any clues as to why the popup is closing abruptly.

**Expected behavior**
The Google Pay Express Checkout popup does Not close automatically on our website's cart page.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Funtouch OS
 - Browser: Chrome
 - Version 116.0.5845.110

**Comment by sarfarazbheda** [comment] 2024-04-04 07:13
@meetvora69  yes Also just to add more notes on above.

- This happens only with Android and Chrome browser.
- If we use different browser like Firefox and Default OS browser then it working fine on Android phone
- Also In Chrome it shows the Google pay pop up otherwise in all other cases it redirect to Pay.google.com site to make payment.

I think for the Chrome also, if we can set redirection then this will be fixed

**Comment by candemiralp** [comment] 2024-04-23 12:15
Hello @meetvora69,

Thank you for creating this issue. The description reminds me an old issue that was solved on #72. Could you please check this PR and apply the fix on your end? Please let us know if the issue is persistent after upgrading.

Best regards,
Can

**Comment by candemiralp** [comment] 2024-07-24 14:35
Closing this issue due to inactivity.

**Closed by candemiralp** 2024-07-24 14:35 UTC
